### ISSUE TITLE
JOSS: Comparison to code cited in Greengard et al. 2021

### ISSUE THREAD

**Issue by bonh** [mjcarley/nbi#2]
You cite Greengard et al. 2021 as the basis for your implementation ("NBI implements recent work on high-order
24 solution of boundary integral problems (Greengard et al., 2021) in a form which can be used
25 for a range of engineering applications."). It seems that they provide a reference implementation of their paper at https://github.com/fastalgorithms/fmm3dbie. I have not tested their code or your code, yet.

Perhaps you should make clear how their code and yours differ?

https://github.com/openjournals/joss-reviews/issues/5972

**Comment by bonh** [comment]
That publication by the same sphere of people might be relevant, too.

https://epubs.siam.org/doi/epdf/10.1137/22M1514040

**Comment by mjcarley** [comment]
I have modified paper.md to include a brief statement on how the code relates to Greengard et al:

The intention has been to develop an implementation of the main
elements of [@greengard-oneil-rachh-vico21] in a code which is
relatively easy to use in applications. The principal differences
which a user will note between NBI and the reference implementation of
the method of [@greengard-oneil-rachh-vico21] are: the range of
geometry formats supported, including the widely used GMSH standard;
the use of the standard PETSc iterative solvers; and the ability to
define boundary conditions using a built-in parser for mathematical
expressions.
