### ISSUE TITLE
JOSS: mention your paper?

### ISSUE THREAD

**Issue by bonh** [mjcarley/nbi#3]
I was searching the web looking for papers referencing your library. While I did not find any (perhaps not surprising, your code is still young, but let me know!) I found your arxiv paper https://arxiv.org/pdf/2301.01179.pdf. It is somewhat different, but perhaps you have a different paper in the pipeline which makes use of your library?

**Comment by mjcarley** [comment]
That paper describes a method for the Laplace equation only, i.e. not including the Helmholtz equation, and only in a cylindrical domain. There is not yet a paper in preparation using the current code, but I expect to use it in applications related to an ongoing project in the future.

**Comment by bonh** [comment]
Thank you for the clarification! :+1:
