### ISSUE TITLE
JOSS: your dependecies

### ISSUE THREAD

**Issue by bonh** [mjcarley/nbi#5]
You list four of your packages as dependencies. 

Perhaps you'd like to package them into `nbi` via `git-submodule` or `git-subtree` or ... (there are a bunch of options, don't know which one is best), and automatize the installation?

**Comment by bonh** [comment]
Pasted @mjcarley's comment from https://github.com/openjournals/joss-reviews/issues/5972#issuecomment-1838947294

> I have included the four dependencies mentioned as submodules and updated README.md to include a note on using git clone --recursive when downloading the code.

**Comment by mjcarley** [comment]
Three of the modules are now bundled into the main repository and included in the build scripts. The exception is blaswrap, because that is a dependency for the submodules (it is no more than a wrapper for BLAS) and I did not want to have multiple versions of it in the dependencies and subdependencies. 

The README.md now lists the dependencies of the submodules as well as of NBI proper to allow installation of those libraries before trying to install the submodules.

**Comment by bonh** [comment]
Awesome! I'll try it later. 

In the new `README` it says:

> To install NBI, you will need to install some or all of the following

Later, it says:

> NBI and a number of its dependencies use a wrapper to interface with BLAS, which you need to install first.

and
> You will also need the GMSH API library

That way it gets confusing what's really required. This description:
> If you are installing the AGG geometry library from within this tree, you will need to install Christian Woltering's API for Jonathan Shewchuk's Triangle code
is very helpful.

Perhaps it would be easier if you separate dependencies into requirements and added functionalities. And I prefer a nice description which package adds which functionality. :smile:

**Comment by mjcarley** [comment]
On 2023-12-12 10:24, Henning Bonart wrote:
> Awesome! I'll try it later.
> 
> In the new README it says:
> 
>> To install NBI, you will need to install some or all of the
>> following
> 
> Later, it says:
> 
>> NBI and a number of its dependencies use a wrapper to interface with
>> BLAS, which you need to install first.
> 
> and
> 
>> You will also need the GMSH API library
> 
> That way it gets confusing what's really required. This description:
> 
>> If you are installing the AGG geometry library from within this
>> tree, you will need to install Christian Woltering's API for
>> Jonathan Shewchuk's Triangle code
>> is very helpful.
> 
> Perhaps it would be easier if you separate dependencies into
> requirements and added functionalities. And I prefer a nice
> description which package adds which functionality. 😄

I have rewritten README.md to say which packages are required and which 
optional, with a short note to say what the optional packages do.

**Comment by bonh** [comment]
> Have you thought about including the dependencies in the build script of `nbi` ?

Hi @mjcarley, have you made a decision concerning the "automated package management solution"?

**Comment by mjcarley** [comment]
The additional packages, other than blaswrap, are now included in the repository and are downloaded and installed if the --recursive option is used when cloning the repository.

**Comment by bonh** [comment]
```
./autogen.sh
./configure
...
./configure: line 10971: syntax error near unexpected token `avx,'
./configure: line 10971: `AX_GCC_X86_CPU_SUPPORTS(avx, hasavx=yes)'
```

**Comment by mjcarley** [comment]
This seems to be the same problem with m4 search paths. I have moved the relevant m4 macros into the m4 directory as with the other package.
